---
# ConfigMap for Backend Environment Variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: ansible-backend-env
  namespace: awx
data:
  .env: |
    # ==========================================
    # Keycloak SSO 설정
    # ==========================================
    KEYCLOAK_SERVER_URL=http://192.168.64.26:30002
    KEYCLOAK_REALM=ansible-realm
    KEYCLOAK_CLIENT_ID=ansible-builder-client
    KEYCLOAK_CLIENT_SECRET=

    # ==========================================
    # Database 설정
    # ==========================================
    # Kubernetes AWX PostgreSQL 연결
    DATABASE_URL=postgresql://awx:dXtiuURqw5iZDWO0RwyEghptyydvMgSo@awx-postgres-15.awx.svc.cluster.local:5432/awx

    # ==========================================
    # AWX 통합 설정
    # ==========================================
    # Execute via AWX 기능에서 자동으로 사용되는 AWX 인증 정보
    # AWX는 OAuth2 토큰 인증을 사용합니다
    AWX_URL=http://192.168.64.26:30000
    AWX_TOKEN=A6tZWbC5pFXUynXvhogzzC0BDWulOj

    # ==========================================
    # 참고사항
    # ==========================================
    # 모든 사용자 인증은 Keycloak SSO를 통해 관리됩니다
    # AWX 작업 실행은 서비스 계정(admin)을 통해 자동으로 처리됩니다
    # 프로덕션 환경에서는 HTTPS 사용을 권장합니다
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-backend
  namespace: awx
spec:
  selector:
    matchLabels:
      app: ansible-backend
  template:
    metadata:
      labels:
        app: ansible-backend
    spec:
      containers:
      - name: backend
        image: ansible-builder-backend:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: ANSIBLE_HOST_KEY_CHECKING
          value: "False"
        - name: PYTHONUNBUFFERED
          value: "1"
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: env-config
          mountPath: /app/.env
          subPath: .env
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: env-config
        configMap:
          name: ansible-backend-env
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: awx
spec:
  selector:
    app: ansible-backend
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-frontend
  namespace: awx
spec:
  selector:
    matchLabels:
      app: ansible-frontend
  template:
    metadata:
      labels:
        app: ansible-frontend
    spec:
      containers:
      - name: frontend
        image: ansible-builder-frontend:v6
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ansible-frontend
  namespace: awx
spec:
  type: NodePort
  selector:
    app: ansible-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
